### ISSUE TITLE
Refactor main.go

### ISSUE THREAD

**Issue by ntaylor1781** [ntaylor1781/k8stk#6]
If we want to add other functionality, main.go should probably be refactored. My initial thought process is to have main.go handle parsing of command args, and calling necessary code elsewhere. We also will need to utilize the go-flags sub-command functionality instead of having it default to just merging configs.

**Comment by ntaylor1781** [comment]
@majgis I am interested in your opinions on this.

**Comment by ghost** [comment]
Agreed.  It makes sense to push config merging to a subcommand and break it out of main.go
